llm:
  api_type: "openai"
  model: "gpt-4-turbo-preview"  # or gpt-3.5-turbo-1106 / gpt-4-1106-previewgit
  base_url: "https://api.openai.com/v1"  # or forward url / other llm url
  api_key: "YOUR OpenAI API Key"
repair_llm_output: true

mermaid:
  engine: "nodejs"
  path: "mmdc"
  puppeteer_config: "/app/metagpt/config/puppeteer-config.json"
  pyppeteer_path: "/usr/bin/chromium"
